title = "Kamil Zakolski"

theme = "hugo-coder"

defaultContentLanguage = "pl"
languageCode = "pl"
#defaultContentLanguageInSubdir = true

enableEmoji = true
paginate = 20

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
noClasses = false

[params]
author = "Kamil Zakolski"
avatarURL = "images/avatar.jpg"
dateFormat = "2 January, 2006"
description = "Prywatna strona Kamila Zakolskiego"
info = ["Specjalista IT", "Student"]
keywords = "blog,developer,personal"
since = 2020

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5

[[params.social]]
icon = "fa fa-2x fa-github"
name = "Github"
url = "https://github.com/KamilZakolski/"
weight = 1

[[params.social]]
icon = "fa fa-2x fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/kamilzakolski/"
weight = 2

[languages.pl]
languageName = ":poland:"

[[languages.pl.menu.main]]
name = "O Mnie"
url = "about/"
weight = 1

[[languages.pl.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.pl.menu.main]]
name = "Kursy"
url = "courses/"
weight = 2

[[languages.pl.menu.main]]
name = "Sprzęt"
url = "hardware/"
weight = 3

[languages.en]
languageName = ":gb:"

[languages.en.params]
dateFormat = "January 2, 2006"
description = "Kamil Zakolski's personal website"
info = ["IT Specialist", "Student"]
keywords = "blog,developer,personal"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Courses"
url = "courses/"
weight = 2

[[languages.en.menu.main]]
name = "Hardware"
url = "hardware/"
weight = 3
