title = "Kamil Zakolski"

theme = "hugo-coder"

languageCode = "pl"
defaultContentLanguage = "pl"
#defaultContentLanguageInSubdir = true

paginate = 20
enableEmoji = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
noClasses = false

[params]
author = "Kamil Zakolski"
avatarURL = "images/avatar.jpg"
description = "Prywatna strona Kamila Zakolskiego"
info = ["Specjalista IT", "Student"]
keywords = "blog,developer,personal"
dateFormat = "2 January, 2006"
since = 2020

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/KamilZakolski/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/kamilzakolski/"

[languages.pl]
languageName = ":poland:"

[[languages.pl.menu.main]]
name = "O Mnie"
weight = 1
url = "about/"

[[languages.pl.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pl.menu.main]]
name = "Sprzęt"
weight = 3
url = "hardware/"

[languages.en]
languageName = ":gb:"

[languages.en.params]
description = "Kamil Zakolski's personal website"
info = ["IT Specialist", "Student"]
keywords = "blog,developer,personal"
dateFormat = "January 2, 2006"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Hardware"
weight = 3
url = "hardware/"